export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const APPOINTMENTS_SUCCESS = 'APPOINTMENTS_SUCCESS';
export const APPOINTMENTS_ERROR = 'APPOINTMENTS_ERROR';
export const ANIMALS_SUCCESS = 'ANIMALS_SUCCESS';
export const ANIMALS_ERROR = 'ANIMALS_ERROR';